---
- name: Configure VLANs, DHCP Pools, and Interface Ports
  hosts: switch  # Replace with the appropriate host or group
  gather_facts: no  # Disable fact gathering for network devices
  become: yes  # Use privilege escalation to execute commands as a privileged user (if needed)

  tasks:
    - name: Create VLANs
      ios_command:
        commands:
          - configure terminal
          - vlan 10
          - name WIFIVLAN
          - exit
          - vlan 50
          - name IPCCTVLAN
          - exit
          - vlan 100
          - name VOICEVLAN
          - exit
      vars:
        ansible_network_os: ios  # Specify the network OS (Cisco IOS)
      register: result_create_vlans

    - name: Configure DHCP Pools
      ios_command:
        commands:
          - configure terminal
          - ip dhcp Excluded-add 10.71.1.1 10.71.1.100
          - ip dhcp Excluded-add 10.71.10.1 10.71.10.100
          - ip dhcp Excluded-add 10.71.50.1 10.71.50.100
          - ip dhcp Excluded-add 10.71.100.1 10.71.100.100
          - ip dhcp pool MGMTDATA
          - network 10.71.1.0 255.255.255.0
          - default-router 10.71.1.4
          - domain-name MGMTDATA.COM
          - dns-server 10.71.1.10
          - exit
          - ip dhcp pool WIFIDATA
          - network 10.71.10.0 255.255.255.0
          - default-router 10.71.10.4
          - domain-name WIFIDATA.COM
          - dns-server 10.71.1.10
          - exit
          - ip dhcp pool IPCCTV
          - network 10.71.50.0 255.255.255.0
          - default-router 10.71.50.4
          - domain-name IPCCTV.COM
          - dns-server 10.71.1.10
          - exit
          - ip dhcp pool VOICEVLAN
          - network 10.71.100.0 255.255.255.0
          - default-router 10.71.100.4
          - domain-name VOICEVLAN.COM
          - dns-server 10.71.1.10
          - option 150 ip 10.71.100.8
          - exit
      vars:
        ansible_network_os: ios
      register: result_configure_dhcp_pools

    - name: Configure Interface Ports
      ios_command:
        commands:
          - configure terminal
          - interface FastEthernet0/2
          - switchport mode access
          - switchport access vlan 10
          - exit
          - interface FastEthernet0/4
          - switchport mode access
          - switchport access vlan 10
          - exit
          - interface FastEthernet0/6
          - switchport mode access
          - switchport access vlan 50
          - exit
          - interface FastEthernet0/8
          - switchport mode access
          - switchport access vlan 50
          - exit
          - interface FastEthernet0/3
          - switchport mode access
          - switchport access vlan 100
          - exit
          - interface FastEthernet0/5
          - switchport mode access
          - switchport access vlan 100
          - exit
          - interface FastEthernet0/7
          - switchport mode access
          - switchport access vlan 100
          - exit
      vars:
        ansible_network_os: ios
      register: result_configure_ports

#  OSPF ROUTING FOR COREBABA

    - name: OSPF 1 COREBABA
      ios_command:
        commands:
          - configure terminal
          - router ospf 1
          - router-id 10.71.71.4
          - network 10.71.0.0 0.0.255.255 area 0
          - int gi 0/1
          - ip ospf network point-to-point
          - end
      vars:
        ansible_network_os: ios
